// Dialect-aware DDL generation for user-defined entities. Pure functions (no DB access) so they
// are easy to unit-test. The catalog (dwh_entities/dwh_columns) is the source of truth; these turn
// catalog rows into CREATE TABLE / ALTER TABLE statements for either SQLite (D1) or Postgres.
//
// NOTE: the Postgres adapter's translate() only rewrites date()/? — it does NOT translate DDL or
// types, so these functions must emit dialect-correct SQL directly, keyed off env.DB_DIALECT.

export type Dialect = "sqlite" | "postgres";

export type DataType =
    | "text"
    | "integer"
    | "real"
    | "boolean"
    | "date"
    | "datetime"
    | "reference";

export const DATA_TYPES: DataType[] = [
    "text", "integer", "real", "boolean", "date", "datetime", "reference",
];

export interface ColumnSpec {
    name: string;
    data_type: DataType;
    is_nullable?: boolean;
    is_unique?: boolean;
    default_value?: string | null;
    // Physical table this reference column points at (required when data_type === "reference").
    ref_physical_table?: string | null;
}

// Identifier policy: lowercase, starts with a letter, only [a-z0-9_]. Used for table and column
// names everywhere they get interpolated into SQL. Reserved/dangerous names rejected separately.
const IDENT_RE = /^[a-z][a-z0-9_]*$/;

const RESERVED = new Set([
    "id", // surrogate PK is added automatically and must not collide
    "select", "from", "where", "table", "order", "group", "by", "join", "insert",
    "update", "delete", "drop", "alter", "create", "index", "primary", "key", "and", "or",
]);

export function safeIdent(name: string): string {
    if (typeof name !== "string" || !IDENT_RE.test(name)) {
        throw new Error(`Invalid identifier "${name}" (use lowercase letters, digits, underscore; start with a letter)`);
    }
    return name;
}

// Like safeIdent but also rejects reserved words / the auto `id` column. Use for user-supplied
// column names; physical table names are generated by us so they only need safeIdent.
export function safeColumnName(name: string): string {
    safeIdent(name);
    if (RESERVED.has(name)) {
        throw new Error(`Column name "${name}" is reserved`);
    }
    return name;
}

export function resolveDialect(value: string | undefined): Dialect {
    return value === "postgres" ? "postgres" : "sqlite";
}

// Physical column type per dialect. Reference columns are plain integer ids.
export function mapType(dataType: DataType, dialect: Dialect): string {
    switch (dataType) {
        case "text": return "TEXT";
        case "integer": return "INTEGER";
        case "real": return dialect === "postgres" ? "DOUBLE PRECISION" : "REAL";
        case "boolean": return dialect === "postgres" ? "BOOLEAN" : "INTEGER";
        case "date": return dialect === "postgres" ? "DATE" : "TEXT";
        case "datetime": return dialect === "postgres" ? "TIMESTAMP" : "TEXT";
        case "reference": return "INTEGER";
        default: throw new Error(`Unknown data type "${dataType}"`);
    }
}

function primaryKeyClause(dialect: Dialect): string {
    return dialect === "postgres" ? "id SERIAL PRIMARY KEY" : "id INTEGER PRIMARY KEY AUTOINCREMENT";
}

// Render a default value literal. Numbers/booleans pass through; everything else is quoted.
function defaultLiteral(value: string, dataType: DataType, dialect: Dialect): string {
    if (dataType === "integer" || dataType === "real") return String(Number(value));
    if (dataType === "boolean") {
        const truthy = value === "1" || value.toLowerCase() === "true";
        return dialect === "postgres" ? (truthy ? "TRUE" : "FALSE") : (truthy ? "1" : "0");
    }
    return `'${value.replace(/'/g, "''")}'`;
}

// Column definition fragment as used inside CREATE TABLE (full constraints allowed there).
function columnFragment(col: ColumnSpec, dialect: Dialect): string {
    const parts = [safeColumnName(col.name), mapType(col.data_type, dialect)];
    if (col.is_unique) parts.push("UNIQUE");
    if (col.is_nullable === false) parts.push("NOT NULL");
    if (col.default_value != null && col.default_value !== "") {
        parts.push(`DEFAULT ${defaultLiteral(col.default_value, col.data_type, dialect)}`);
    }
    if (col.data_type === "reference" && col.ref_physical_table) {
        parts.push(`REFERENCES ${safeIdent(col.ref_physical_table)}(id)`);
    }
    return parts.join(" ");
}

export function createTableSQL(physicalTable: string, columns: ColumnSpec[], dialect: Dialect): string {
    const table = safeIdent(physicalTable);
    const cols = [primaryKeyClause(dialect), ...columns.map(c => columnFragment(c, dialect))];
    return `CREATE TABLE ${table} (\n    ${cols.join(",\n    ")}\n)`;
}

// ALTER TABLE ... ADD COLUMN. SQLite cannot add UNIQUE columns, and a NOT NULL column needs a
// non-null default — so for SQLite we relax those (the column is added nullable). A reference
// column is added with an inline REFERENCES, which SQLite permits only when nullable/default-NULL.
export function addColumnSQL(physicalTable: string, col: ColumnSpec, dialect: Dialect): string {
    const table = safeIdent(physicalTable);
    const parts = [safeColumnName(col.name), mapType(col.data_type, dialect)];

    const canUnique = dialect === "postgres";
    const hasDefault = col.default_value != null && col.default_value !== "";

    if (col.is_unique && canUnique) parts.push("UNIQUE");
    // NOT NULL only when we can satisfy it (Postgres always; SQLite only with a default).
    if (col.is_nullable === false && (dialect === "postgres" || hasDefault)) parts.push("NOT NULL");
    if (hasDefault) parts.push(`DEFAULT ${defaultLiteral(col.default_value as string, col.data_type, dialect)}`);
    if (col.data_type === "reference" && col.ref_physical_table) {
        parts.push(`REFERENCES ${safeIdent(col.ref_physical_table)}(id)`);
    }
    return `ALTER TABLE ${table} ADD COLUMN ${parts.join(" ")}`;
}

// The ER-playground "create connection": add a nullable integer reference column. This is the only
// post-creation FK form SQLite/D1 accepts (nullable, default NULL).
export function addReferenceColumnSQL(
    physicalTable: string,
    columnName: string,
    refPhysicalTable: string,
    dialect: Dialect,
): string {
    return addColumnSQL(
        physicalTable,
        { name: columnName, data_type: "reference", is_nullable: true, ref_physical_table: refPhysicalTable },
        dialect,
    );
}

// Reference column WITHOUT the inline constraint — fallback if D1 rejects ADD COLUMN ... REFERENCES.
// The FK then lives only in the catalog (logical FK); app-level cascade still works.
export function addReferenceColumnSQLNoConstraint(physicalTable: string, columnName: string): string {
    return `ALTER TABLE ${safeIdent(physicalTable)} ADD COLUMN ${safeColumnName(columnName)} INTEGER`;
}

export function dropTableSQL(physicalTable: string): string {
    return `DROP TABLE IF EXISTS ${safeIdent(physicalTable)}`;
}

// Physical table name for a managed entity: d_{projectId}_{name}.
export function physicalTableName(projectId: number, entityName: string): string {
    return safeIdent(`d_${projectId}_${safeColumnName(entityName)}`);
}
