name = "api-controller"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
DB_DIALECT = "sqlite"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "db-prod"
database_id = ""

[[d1_databases]]
binding = "CHAT_DB"
database_name = "chat-db"
database_id = ""
